version: '3.7'

services:
  app:
    build: 
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ./BoSProject/.env
    depends_on:
      - db
  db:
    image: "postgres:15"
    ports:
      - "5432:5432"
    env_file:
      - ./BoSProject/.env
    volumes:
      - BoSProject-volume:/var/lib/postgresql/data

volumes:
  BoSProject-volume: 